name: Check if test suites workable
on:
  workflow_call:

jobs:
  pre_job:
    name: "Skip test if already executed"
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          skip_after_successful_duplicate: 'true'

  execute_test_suite:
    name: "Execute test suites on denmark tester"
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Pull xoa-regression-tests
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.AUTOTEST }}
          repository: xenanetworks/xoa-regression-tests
          path: ./xoa-regression-tests
          submodules: recursive

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install tox and any other packages
        run: pip install tox

      - name: Replace deps as current repo and branch
        working-directory: ./xoa-regression-tests
        run: |
          python actions_override_deps.py --event_name ${{ github.event_name }} --event_repo ${{ github.event.repository.name }} --event_branch ${{ github.head_ref || github.ref_name }} --core_branch ${{ github.event.inputs.core_branch || 'dev' }} --converter_branch ${{ github.event.inputs.converter_branch || 'dev' }} --driver_branch ${{ github.event.inputs.driver_branch || 'dev' }} 
          cat git-requires.txt

      - name: Run tox
        working-directory: ./xoa-regression-tests
        run: TEST_SUITES_BRANCH=${{ github.event.inputs.test_suites_branch || 'dev' }} tox -e git-demo-tester -r

concurrency:
  # group: ${{ github.head_ref || github.ref_name }}
  group: ${{ github.workflow }} # github do not have queue https://github.com/community/community/discussions/12835
  cancel-in-progress: true
